import { ATTENDANCE, OFFICE, ROLE, USER } from "./collection.constants";
import { ALREADY_EXISTS, DATA_NOT_FOUND, NOT_FOUND } from "./common.constants";



export const {
    // Auth
    USER_NOT_FOUND = USER + NOT_FOUND,
    EMAIL_VALIDATION_FAILED = "Email validation failed.",
    INVALID_PASSWORD = "The provided password is incorrect.",
    NO_USER_ID_IN_PAYLOAD = "The user ID was not included in the payload by the authentication middleware.",
    AUTHORIZATION_FAILED = "Authorization procedure failed at the server.",
    SERVER_ISSUE = "An error occurred at the server. Please try again later.",
    ACCESSTOKEN_MISSING = "Access token is missing from the header after authentication middleware.",
    INVALID_OTP = "Email verification failed. Invalid OTP.",

    // Custom Roles Handling
    CUSTOM_ROLE_ALREADY_EXISTS = "The requested custom role already exists.",
    ROLE_DATA_NOT_FOUND = ROLE + DATA_NOT_FOUND,
    INVALID_ID = "Invalid unique ID provided.",
    ROLE_ALREADY_EXISTS = "Cannot update as the role name already exists.",
    ROLE_NOT_FOUND = "The requested role was not found.",
    INVALID_ROLE = "Invalid role provided.",
    INSUFFICIENT_PRIVILEGES = "Forbidden: Insufficient role privileges.",

    // User Handling
    NO_OFFICE_ASSIGNMENT = "You are not assigned to any office and cannot take any action.",
    INVALID_EMAIL_ID = "Invalid email ID provided.",
    EMAIL_NOT_SENT = "Error occurred while sending the email.",
    USER_ALREADY_EXISTS = USER + ALREADY_EXISTS,
    USER_DATA_NOT_FOUND = USER + DATA_NOT_FOUND,
    ACCESS_RESTRICTED_TO_ASSIGNED_OFFICE = "You are only authorized to access employees of the assigned office.",
    EMAIL_ALREADY_IN_USE = "The email address you entered is already associated with your account.",

    // Office Handling
    LOCATION_NOT_MATCHED = "The location does not match the provided address.",
    OFFICE_ALREADY_EXISTS_AT_LOCATION = "An office already exists at the specified location.",
    OFFICE_DATA_NOT_FOUND = OFFICE + DATA_NOT_FOUND,
    OFFICE_NOT_FOUND = OFFICE + NOT_FOUND,
    USER_ALREADY_IN_OFFICE = "The requested user has already been added to this office.",
    USER_IN_OTHER_OFFICE = "The requested user has already been added to another office.",
    NOT_PERMITTED_AS_MANAGER = "User is not permitted to be assigned as a manager.",
    INVALID_OFFICE_USER_ROLE = "You can only assign or remove a user as either a manager or an employee to an office.",
    MANAGER_NOT_FOUND_IN_OFFICE = USER_NOT_FOUND + ', As Manager in the given office',
    EMPLOYEE_NOT_FOUND_IN_OFFICE = USER_NOT_FOUND + ', As Employee in the given Office',
    TRASH_EMPTY = "Your trash is empty.",
    OFFICE_NOT_FOUND_IN_TRASH = "The requested office was not found in the trash.",

    // Attendance Handling
    NO_OFFICE_ASSIGNMENT_PUNCH = "You cannot punch in or punch out without being assigned to an office.",
    DELETED_OFFICE_ID_STILL_ASSOCIATED = "Deleted office ID is still associated with the user. System failure!",
    INVALID_ATTENDANCE_LOCATION = "Request made from an invalid location. You are not permitted to mark attendance from this location.",
    NO_OFFICES_AVAILABLE_FOR_MARK_ATTENDANCE = "No offices are available in the system to mark attendance.",
    ALREADY_PUNCHED_IN_TODAY = "You have already punched in once today.",
    PUNCH_IN_REQUIRED_BEFORE_PUNCH_OUT = "You must punch in before punching out.",
    PUNCH_IN_BEFORE_PUNCH_OUT = "Punch in time must before punching out.",
    ALREADY_PUNCHED_OUT_TODAY = "You have already completed punch-out for today.",
    ERROR_FETCHING_OFFICE_DATA = "Something went wrong while fetching existing office data.",
    CANNOT_MARK_FUTURE_ATTENDANCE = "Attendance cannot be marked for a future date.",
    USER_ALREADY_HAS_ATTENDANCE = "The provided user already has attendance data for the given date.",
    ATTENDANCE_NOT_FOUND = "Attendance record not found.",
    USER_NOT_FOUND_ASSOCIATED_WITH_ATTENDANCE = "User associated with the attendance record not found.",
    OFFICE_ID_NOT_FOUND_IN_SYSTEM = "The office ID on the user record does not exist in the system.",
    USER_NOT_ASSIGNED_TO_OFFICE = "The given user is not assigned to any office.",
    USER_DATA_NOT_FOUND_OF_ATTENDANCE = "User data of the existing attendance record was not found.",
    CANNOT_FILTER_FUTURE_ATTENDANCE = "Future attendance data cannot be filtered.",
    ATTENDANCE_DATA_NOT_FOUND = ATTENDANCE + DATA_NOT_FOUND,
    NO_ATTENDANCE_HISTORY_IN_DATE_RANGE = "The user has no attendance history between the given date range.",

    // Validation
    VALIDATION_FAILED = "Validation failed.",
    INVALID_REQUEST_BODY = "Invalid request body.",
    INVALID_REQUEST_QUERY = "Invalid request query.",
    CLIENT_SIDE_REQUEST_FAILED = "An error occurred while processing the request on the client side.",
    REQUEST_FAILED = "Oops, the request failed!",
    PUNCH_IN_OR_OUT_REQUIRED = "Either punch-in or punch-out argument is required.",
    INVALID_TIME_FORMAT = "Invalid time format. It must be an ISO string.",
    INVALID_PUNCH_IN_OUT_COMPARISON = "No data provided for comparison. Invalid usage of punch-in and punch-out time comparison.",
    FAILED_TO_SEND_OTP_EMAIL = "Failed to send OTP email. Please try again.",
    INVALID_DAYS_PROVIDED = "Invalid days provided. Ensure all days are valid enum values and separated by commas.",
    LATITUDE_REQUIRED = "Latitude is required.",
    LONGITUDE_REQUIRED = "Longitude is required.",
    AT_LEAST_REQUIRED_ARTTENDACE_CREATION = "At least one field is required. If a date is provided, both punchInTime and punchOutTime must be provided.",
    PAGE_NUMBER_REQUIRED = "Page number is required.",
    PAGE_LIMIT_REQUIRED = "Page limit is required.",
    INVALID_SORT_KEY = "Invalid sort key.",
    PAGE_NUMBER_MUST_BE_DIGITS = "Page number must be provided in digits.",
    PAGE_LIMIT_MUST_BE_DIGITS = "Page limit must be provided in digits.",
    CONFLICTING_ATTENDANCE_FILTER_PARAMETERS = "You cannot provide startDate, endDate, or days along with date when filtering attendance data.",
    INSUFFICIENT_FEILDS_ON_DATE_RANGE = "endDate must be provided if startDate is provided.",
    INVALID_DATE_RANGE = "startDate must be less than or equal to endDate.",
    DATE_IS_REQUIRED = 'Date is required',
    INVALID_DATE_FORMAT = "Date must be in YYYY-MM-DD format.",
    PUNCH_IN_OUT_TIME_REQUIRED = "Both punch-in and punch-out times must be provided.",
    INVALID_TIME_INPUT = "Invalid time format. Expected HH:MM in 24-hour format.",
    OFFICE_NAME_REQUIRED = "Office name is required.",
    STREET_REQUIRED = "Street is required.",
    CITY_REQUIRED = "City is required.",
    STATE_REQUIRED = "state is required",
    ZIP_CODE_REQUIRED = "zip code is required",
    RADIUS_REQUIRED = "radius required and should be calculated in meters",
    LAT_LONG_REQUIRED_FOR_ADDRESS_UPDATE = "Latitude and longitude must be provided when any address field (street, city, state, or zip_code) is updated.",
    ADDRESS_FIELDS_REQUIRED_FOR_LOCATION_UPDATE = "Address fields (street, city, state, zip_code) must be updated when location (latitude or longitude) is modified.",
    AT_LEAST_ONE_FIELD_REQUIRED_FOR_UPDATE = "At least one field is required for update.",
    INVALID_OTP_FORMAT = "OTP must be a 6-digit number.",
    INVALID_PASSWORD_FORMAT = "Password must be at least 8 characters long and include at least one letter, one number, and one special character.",
    INVALID_PHONE_NUMBER_FORMAT = "Invalid phone number format",
    INVALID_PERMISSION_LEVEL = "Permission level should be 'all', 'group', or 'own'.",
    ROLE_NAME_REQUIRED = "Role name is required.",
    CANNOT_BE_DEFAULT_ROLE = "Role cannot be one of the default roles.",
    PERMISSION_FIELD_REQUIRED = "At least one permission field is required.",
    REQUIRED_FOR_ROLE_UPDATE = "Role or permission fields are required for updation.",
    USERNAME_REQUIRED = "Username is required.",
    USERNAME_MIN_LENGTH = "Username must be at least 5 characters long.",
    EMAIL_REQUIRED = "Email is required.",
    INVALID_EMAIL_FORMAT = "Invalid email format.",
    ROLE_REQUIRED = "Role is required.",
    PASSWORDS_MUST_MATCH = "Passwords do not match with the confirm password field.",
    INVALID_TIMEZONE = "Invalid timezone format.",
    INVALID_DATE_ISO = "Invalid date provided.",
    INVALID_DATE_AS_DATE = "Invalid date format of stringified date object.",
    NO_TIMEZONE_FOUND = "No timezone found for the given coordinates.",
    INVALID_INPUT_PARAMETERS = "Invalid input parameters.",
    INVALID_SEARCH_KEY="Search key should be string"
} = {} as const;